### ISSUE TITLE
Library feature

### ISSUE THREAD

**Issue by charlee-dev** [voize-gmbh/reakt-native-toolkit#12]
Hi. Just a few questions.
- What are the plans for this library?
- Will it be maintained?
- What is the current state?

**Comment by Legion2** [comment]
We are actively using this library and update it to a new react native version if we have time for it.
Next supported React Native version should be 0.71 or higher. This brings huge improvements to the compatibility and publishing of this library, see https://github.com/reactwg/react-native-new-architecture/discussions/105. But until then the library is only compatible with react native 0.69.4.

If you find bugs, we are open for PRs.

**Comment by charlee-dev** [comment]
Thanks for the quick response!

I am a Kotlin developer working on an RN project with Koltin Multiplatform Sdk. I'm ofc working on the SDK part.
In our setup, we publish KMM SDK as a library for RN Android, and for the iOS part, we pack it as XCFramework, and both of them are moved into the RN project.
In my day-to-day life, I need to change the RN bridging code in Android Kotlin and iOS Swift code. While working on the SDK, the Android RN project is not enabled in settings.gradle, so we have no code completion in the RN Android module, and we need to open Xcode to update the code. 

So I decided to change it. I created a separate KMM module, "bridge", where I can put all the bridging code nice and tidy. I moved Android RN stuff, and all worked as expected, no surprise. Moving iOS bridging code, and converting it to Kotlin so it works with ObjC is a different story of trial and error. But then I found your library, and it looks like my problem was your problem before, and you solved it, which is excellent!

Question:
If the library is currently tied to the React Native version 0.69.4, is it backwards compatible too? Or does it need to be the exact version? We are currently on RN 0.67.3.

**Comment by Legion2** [comment]
Hi,
Regarding your question, technically supporting different  RN version is possible, but currently because old RN Android versions are not available in maven repo you get an error wenn your local RN version is not the same as the version specified in the library. Maybe we can change the specific version to a wildcard in Gradle.

Next week I have to work on toolkit to improve the EventEmitter support on iOS. Maybe I can check on that too.

**Comment by Legion2** [comment]
@charlee-dev we made a new release with updated react native version, you may want to try to use this release in your app with older react native version. You may need to build the toolkit locally to adjust the rn version. There is now also an example project which may help you integrate the toolkit.

**Comment by charlee-dev** [comment]
Thank you. I'll give it a go soon. I will let you know if I need help, but I'll open a new issue, if I do. 🤞
