### ISSUE TITLE
Parameter 'args' is never used, could be renamed to _

### ISSUE THREAD

**Issue by charlee-dev** [voize-gmbh/reakt-native-toolkit#21]
Generated code in build dir for ios contains unused args, resulting in the build output warning.

> "Parameter 'args' is never used, could be renamed to _"

To reproduce, create a suspended function with no properties:
```kotlin
@ReactNativeMethod
fun getInfo(): String {
    return SDK.deviceManager.getInfo().asString()
}
```

Results with generated code:
```kotlin
RCTBridgeMethodWrapper("getInfo") { args, promise -> getInfo(promise as
      PromiseIOS<String>)}
```

**Comment by Legion2** [comment]
Thanks for reporting this. We will address this in an upcoming release.
