### ISSUE TITLE
Error with useFlow

### ISSUE THREAD

**Issue by guyaumetremblay** [voize-gmbh/reakt-native-toolkit#32]
Hi, 

I'm trying to use a module returning a flow but I'm receiving this error: 
```
Next value promise in useFlow was rejected: Error: NoSuchElementException: Expected at least one element matching the predicate (kotlin.String) -> kotlin.Boolean
```

My module look like this: 
```
@ReactNativeModule("FooUseCase")
class FooUseCaseRN(private val fooUseCase: FooUseCase) {
    @ReactNativeFlow
    suspend fun getFoo(): Flow<List<String>> {
        [Some code returning a flow]
    }
}
```
(I saw from the debugger that the code from the method getFoo is called and working)
I tried returning only a string instead of a list of string, thinking that it is working only for primitive, but I got the same error.

The generated modules.ts look like this: 
```
// This file is generated by ReaktNativeToolkit. Do not edit.
import {NativeEventEmitter, NativeModules} from 'react-native';
import {Next} from 'reakt-native-toolkit';


interface NativeFooUseCaseInterface {

  getFoo: Next<Array<string>>;

}

/**
 * Module generated from {@link com.bar.baz.usecase.FooUseCaseRN}.
 */
export interface FooUseCaseInterface {

  getFoo: Next<Array<string>>;

}

type _workaround = NativeEventEmitter;

const NativeFooUseCase = NativeModules.FooUseCase as NativeFooUseCaseInterface
export const FooUseCase: FooUseCaseInterface = {
  ...NativeFooUseCase,
  getFoo: (currentValue: string | null) => NativeFooUseCase.getFoo(currentValue)
}
```

Finally, in my view, I'm calling it like this: 
```
const foo = useFlow(FooUseCase.getFoo);
```

Any idea what could happen?

**Comment by guyaumetremblay** [comment]
Hi again, 
Just found, by looking at the example, that we need to specify an `onStart` value to our `Flow`. 
So, I updated my flow creation by appending `.onStart { emptyList() }`
But now, the module is call in an infinite loop!
One time with a `currentValue` of an empty array, followed by a call with the result of the previous one, and again an empty array...

**Comment by Legion2** [comment]
Make sure your flow is semantically equevalent to an StateFlow, it must represent an state, remove the onStart value, because it breaks the StateFlow semantic. From the error message it looks like your flow only returns an finite amount of values and is then completes. UseFlow only makes sense to use with flows which never complete and always represent an state which may change in the future.

**Comment by Legion2** [comment]
I think you are referring to 
```kotlin
getChanges(key).onStart { emit("trigger first load") }
            .map { getConfig(key) }.conflate().distinctUntilChanged()
```

here onStart is only used to trigger an initial load, which is transformed by `map` to the current state. The value emitted in onStart is never returned by the resulting flow.

**Comment by guyaumetremblay** [comment]
Hi,

Thanks for your reply.

My flow is made from a call to my backend. It's state can so be a pending
request, the value or an error. So the content is not final.

If I don't specify an initial value, I received the error. If I add the
onStart, my ui flicker because 1 frame, the list is empty and next frame,
my content is there.
I whish I can give you more to investigate!

Le sam. 14 oct. 2023, 18 h 02, Leon Kiefer ***@***.***> a
écrit :

**Comment by Legion2** [comment]
You cannot use useFlow with such a "request" based flow, because the flow is not consumed once but multiple times. If you just want to call a suspend function from js, use the RectNativeMethod annotation and do not expose a flow. If you need to expose it as flow make it a shared flow, so the request is only done once.

**Comment by guyaumetremblay** [comment]
Hi @Legion2 

I understand what you mean. I'll try both alternative. 
Also, thanks for this lib which I think will be very useful.
