### ISSUE TITLE
ReactNativeModuleBase not resolved in App

### ISSUE THREAD

**Issue by kcn1-71** [voize-gmbh/reakt-native-toolkit#51]
Hi guys!
I'm having a problem building my test application

I followed your instructions from the readme, made a clean Expo module, made a Kotlin multiplatform module, added annotations, generated classes

The problem occurred on Step 4

I'm trying to register a generated class but I'm getting a class incompatibility error.
![Screenshot 2024-04-12 at 19 38 27](https://github.com/voize-gmbh/reakt-native-toolkit/assets/13884986/6e48c1c6-1632-4d68-ad47-11fad84037aa)

Am I missing some step?

**Comment by Legion2** [comment]
The generated class RN module class will be called `{MyClassName}Android`. So it looks right if your RN module class is called `Greeting`.
However you can also skip step 4 and use auto generated [Module Providers](https://github.com/voize-gmbh/reakt-native-toolkit/tree/main?tab=readme-ov-file#streamline-dependency-injection-using-module-providers) instead, they are available in common code and are called `{MyClassName}Provider` you can call `getModule` in android and ios and get the respective platform implementation.

**Comment by kcn1-71** [comment]
Yes, I checked the option with the provider, but got the same error
![Screenshot 2024-04-12 at 21 18 06](https://github.com/voize-gmbh/reakt-native-toolkit/assets/13884986/10027c88-e683-44ad-9661-372c04504dc5)

**Comment by Legion2** [comment]
Ok from the error message I would suspect that you are missing the `de.voize:reakt-native-toolkit` dependency in your project. Can you please follow the Installation instruction from the [Readme](https://github.com/voize-gmbh/reakt-native-toolkit/tree/main?tab=readme-ov-file#installation).

**Comment by kcn1-71** [comment]
The dependency was definitely added to the shared_library project, otherwise the classes would not have been generated. Do I still need to connect reakt-native-toolkit to my Android application?
![Screenshot 2024-04-12 at 21 27 55](https://github.com/voize-gmbh/reakt-native-toolkit/assets/13884986/a0ccff04-ed9f-4001-9f19-f65c07130f7b)

**Comment by Legion2** [comment]
What do you mean with "connect" the "android" project will depend on the "shared" project so you can access the shared code including the generated RN module classes. In which project is the `MyRNPackage` class?

Also, react native 0.20.1 looks odd to me, this is a very old version?

**Comment by Legion2** [comment]
If the MyRNPackage is in you android project you also need to add the toolkit dependency to you android project.

**Comment by Legion2** [comment]
@kcn1-71 do you still need help with the project setup?

**Comment by kcn1-71** [comment]
Yeah, sorry, just forgot to close the issue
