### ISSUE TITLE
Could not find reakt-native-toolkit-iosX64Main-0.16.0.klib

### ISSUE THREAD

**Issue by charlee-dev** [voize-gmbh/reakt-native-toolkit#60]
Hi. The time for dependency update came and i'm are bumping from 0.5.0... so it's been a while... ;) 

When trying to bump to `0.16.0` i get:

```
:bridge:iosX64Main: Could not find reakt-native-toolkit.klib (de.voize:reakt-native-toolkit-iosx64:0.16.0).
Searched in the following locations:
    https://plugins.gradle.org/m2/de/voize/reakt-native-toolkit-iosx64/0.16.0/reakt-native-toolkit-iosx64-0.16.0.klib
```

I successfully managed to sync the`0.15.0`

**Comment by Legion2** [comment]
The search paths do not look right, gradle is looking in the plugin repository for the runtime artifact, but the artifacts are only published to maven central

**Comment by Legion2** [comment]
because 0.5.0 is a very old version, please read the documentation and follow the setup process again to ensure you have configured everything correctly.

**Comment by Legion2** [comment]
Is the sync in the IDE failing or Gradle CLI if called from terminal?

**Comment by charlee-dev** [comment]
Sync in the Android Studio, which made me try IntelliJ, and the sync worked... so it seems the issue is Android Studio-related. Thanks for pointing me in the right direction and closing this.
